on:
  push:
    branches-ignore: [main]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn
      - run: yarn test
      - uses: helloitsjoe/deploy-github-pages@v1
        with:
          build_dir: public
          branch_build: true